[package]
name = "ui"
version.workspace = true
edition.workspace = true

[dependencies]
contracts = { workspace = true }
gpui = { workspace = true }
gpui-component = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
theme = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
