[package]
name = "nexora-updater-macos-example"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
gpui = { version = "0.2.2", git = "https://github.com/zed-industries/zed", rev = "cc053a4a6fa2fd0e8793201ed9099466af1be0b1", default-features = false }
gpui-component = { version = "0.5.2", git = "https://github.com/longbridge/gpui-component", rev = "55b6bb88905d8e76cd23d9e3ebea3151dcdb84a0" }
nexora = { path = "../../crates/nexora", default-features = false, features = ["desktop", "derive"] }
serde = { version = "1", default-features = false, features = ["derive", "std"] }
theme = { path = "../../crates/theme" }

[replace]
"https://github.com/zed-industries/zed#gpui@0.2.2" = { git = "https://github.com/zed-industries/zed", rev = "cc053a4a6fa2fd0e8793201ed9099466af1be0b1" }
"https://github.com/zed-industries/zed#gpui_macros@0.1.0" = { git = "https://github.com/zed-industries/zed", rev = "cc053a4a6fa2fd0e8793201ed9099466af1be0b1" }

[[bin]]
name = "updater-macos"
path = "src/main.rs"

[[bin]]
name = "updater-macos-updater"
path = "src/bin/sidecar.rs"
