[package]
name = "updater"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-channel = { workspace = true }
base64 = { workspace = true }
directories = { workspace = true }
ed25519-dalek = { workspace = true }
getrandom = { workspace = true }
gpui = { workspace = true }
gpui-component = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
zip = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_Foundation", "Win32_Security_Cryptography", "Win32_Security_Cryptography_Certificates", "Win32_Security_WinTrust"] }
windows-sys = { workspace = true, features = ["Win32_Security_Cryptography"] }
